apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-worker
  template:
    metadata:
      labels:
        app: judge0-worker
    spec:
      containers:
        - name: judge0-worker
          image: judge0/judge0:1.13.1
          command: ["./scripts/workers"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: algo-arena-db
                  key: DATABASE_URL
            - name: JUDGE0_URI
              valueFrom:
                secretKeyRef:
                  name: algo-arena-db
                  key: JUDGE0_URI
                  # simple string REDIS_HOST is redis.default.svc.cluster.local
            - name: REDIS_HOST
              value: redis.default.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "asd"
            - name: POSTGRES_HOST
              value: "postgres.default.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "algo-arena"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "supersecurepassword"
          volumeMounts:
            - name: problems-pv
              mountPath: /problems
      volumes:
        - name: problems-pv
          persistentVolumeClaim:
            claimName: problems-claim