apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-pg
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-010e71b2d11234952