name: Build and push Web

on:
  push:
    branches:
      - 'main'
    
jobs:
  Deploy-web:
    name: Builds and pushes to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Copy Docker image to root
        run: cp ./docker/web/Dockerfile .

      - name: Build Docker Image
        run: docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t 100xdevs/algo-next:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push 100xdevs/algo-next:${{ github.sha }}
